<a href="https://colab.research.google.com/github/mahii6991/Kaggle_Projects/blob/main/Numpy_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.array([1,2,2,5,8,4,5,6,5])

array([1, 2, 2, 5, 8, 4, 5, 6, 5])

In [5]:
3*np.array([1,2,3,4,5,6,7,8,9])#we can multiply it with the array

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
arr1 = np.array([3,4,5,6,2,8,9,1,2,3,5,4])

In [8]:
sorted(arr1) #it helps us to arrange the elemnts in the correct order

[1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 8, 9]

In [9]:
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
print(z[2,1])  #the thing to remember is that , in python the counting starts from 0

7


In [11]:
print(z[-1,-1]) #but when we start if from the back , we did not count the zero in it.

8


In [12]:
print(z[2,1]) #the counting of the matrix should be start from 0

7


In [13]:
print(z[-1,-2]) #when starting from the negative values we need to start from 0

7


In [14]:
print(z[2,:]) #way of getting the last row of the matrix

[6 7 8]


In [15]:
print(z[:,0])

[0 3 6]


In [16]:
print(z[1:,1:])

[[4 5]
 [7 8]]


In [17]:
z = np.arange(9).reshape(3,3)

In [18]:
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
z[[0,0],[1,2]]

array([1, 2])

In [20]:
#To get specific indices values such as (0,0) and (1,2) write: (Z[[0,1],[0,2]])

In [21]:
z[1:,1:]

array([[4, 5],
       [7, 8]])