<a href="https://www.kaggle.com/code/mahendrasinghrajpoot/sinch-intent-detection?scriptVersionId=107595166" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Intent Detection

> Importing the libraries

In [40]:
import numpy as np
import pandas as pd

X_train = np.load('../input/intent-detection-by-sinch/X_train.npy')
X_test = np.load('../input/intent-detection-by-sinch/X_test.npy')

y_train = pd.read_csv('../input/intent-detection-by-sinch/y_train.csv').Predicted.to_numpy()#converting it into an numpy array.

In [41]:
def eda_data(X_train , X_test ,y_train):
    print("the dimension of x_train {}".format(X_train.ndim))
    print("the dimension of x_test {}".format(X_test.ndim))
    print("the shape of x_train {}".format(X_train.shape))
    print("the shape of x_test {}".format(X_test.shape))
    print("the size of x_train {}".format(X_train.size))
    print("the size of x_test {}".format(X_test.size))
    print("the size of y_train{}".format(y_train.shape))
    
    

In [42]:
eda_data(X_train,X_test,y_train)

the dimension of x_train 2
the dimension of x_test 2
the shape of x_train (1663, 768)
the shape of x_test (713, 768)
the size of x_train 1277184
the size of x_test 547584
the size of y_train(1663,)


In [43]:
X_train[:10]

array([[-0.06471267,  0.02055361, -0.06917297, ..., -0.02007275,
        -0.052884  ,  0.02371432],
       [-0.00638058,  0.00781697, -0.02294698, ..., -0.06647593,
        -0.01216047,  0.01780251],
       [ 0.0035793 , -0.00922786, -0.06279555, ...,  0.01276198,
         0.0185549 ,  0.00260469],
       ...,
       [-0.03657193, -0.03249233, -0.04902271, ..., -0.02548403,
        -0.00615544,  0.00632733],
       [-0.09880348, -0.00711128, -0.0496961 , ...,  0.04092421,
        -0.03646911, -0.01291262],
       [-0.03984436, -0.00512383, -0.06740589, ...,  0.0279867 ,
        -0.05178341, -0.02997069]], dtype=float32)

In [44]:
X_test[0:5]

array([[-0.02834134, -0.0139755 ,  0.02748156, ...,  0.02481022,
        -0.03690887,  0.04531401],
       [-0.01447345, -0.0372807 ,  0.01781211, ..., -0.00767628,
         0.02581855,  0.0363168 ],
       [-0.02263621, -0.00175439, -0.00981159, ..., -0.05182212,
         0.01489526, -0.04339051],
       [-0.04085005, -0.02305806, -0.03366361, ..., -0.02507613,
         0.04031206,  0.00623322],
       [ 0.00593197, -0.03842481,  0.04876529, ..., -0.04007944,
        -0.0408687 , -0.01490707]], dtype=float32)

In [45]:
y_train[0:3]

array([ 8, 44, 11])

Training the model for the intent detection on the top of the preformatted data or tokenized data.

In [46]:
#loading the sample file into the system 
sample = pd.read_csv("../input/intent-detection-by-sinch/sample.csv")
sample.shape

(713, 2)

In [47]:
import math
from sklearn.model_selection import train_test_split

In [48]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

#fiting the model to the dataset
logreg = LogisticRegression()
logreg.fit(X_train,y_train)

#finding out the accuracy on the test dataset intead of the using some other classification 

y_pred = logreg.predict(X_test)

#printing out the classification report of the dataset        
#print("The classification report of the above dataset is{}".format(classification_report(y_train,y_pred)))
#submission = pd.DataFrame({'id':sample['Id'],'Predicted':y_pred})

In [49]:
#submission.to_csv('submission.csv',index=False)

In [50]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=100)
knn.fit(X_train,y_train)
#making the prediction using the k neares neighbors and checking our the accuracy our of it
y_pred_knn = knn.predict(X_test)
#making the submission file
#submission = pd.DataFrame({'id':sample['Id'],'Predicted':y_pred_knn})


In [51]:
#submission.to_csv('submission.csv',index=False)

# using XGBoost

In [52]:
from xgboost import XGBClassifier

xmodel = XGBClassifier(subsample=0.7,max_depth=4)
print(xmodel)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, gamma=None,
              gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, predictor=None, random_state=None,
              reg_alpha=None, reg_lambda=None, ...)


In [53]:
#xmodel.fit(X_train,y_train)

In [54]:
#prediction_xgb = xmodel.predict(X_test)

In [55]:
#prediction_xgb

In [56]:
#submission_xgb = pd.DataFrame({'Id':sample['Id'],'Predicted':prediction_xgb.flatten()})

In [57]:
#submission_xgb.head()

In [58]:
#submission_xgb.to_csv('submission.csv',index=False)

> finding out the right hyperparameters on the training data,using gridsearch cv

In [59]:
from sklearn.model_selection import GridSearchCV

import warnings
warnings.filterwarnings('ignore')

#parameter grid
parameter= {
    'penalty':['l1','l2'],
    'C':np.logspace(-3,3,7),
    'solver':['newton-cg','lbfgs','liblinear']
}

In [60]:
logreg_cv = LogisticRegression()

clf = GridSearchCV(logreg_cv,param_grid=parameter,scoring='accuracy',cv=10)

In [61]:
#clf.fit(X_train,y_train)

In [62]:
#print("Tuned Hyperparameters:",clf.best_params_)
#print("Accuracy:",clf.best_score_)

In [63]:
Tuned_Hyperparameters: {'C': 10.0, 'penalty': 'l2', 'solver': 'newton-cg'}

In [64]:
tuned_logreg = LogisticRegression(C=10.0, penalty= 'l2', solver= 'newton-cg')

tuned_logreg.fit(X_train,y_train)
tuned_predict = tuned_logreg.predict(X_test)

In [65]:
#submission_tuend_logred = pd.DataFrame({'Id':sample['Id'],'Predicted':tuned_predict.flatten()})

In [66]:
#submission_tuend_logred.to_csv('submission.csv',index=False)

In [67]:
#num_words = min(max_num_words, len(word_index))+1

# using the deep learning

In [68]:
#from here we will start by defining the model.
import keras.backend as K
from keras.layers import Dense , Embedding , LSTM ,SimpleRNN
from keras.models import Sequential

In [83]:
embedding_layer = Embedding(200, 45, input_length=50)

In [70]:
len(X_train)

1663

In [104]:
X_train.shape

(1663, 768)

In [105]:
X_train

array([[-0.06471267,  0.02055361, -0.06917297, ..., -0.02007275,
        -0.052884  ,  0.02371432],
       [-0.00638058,  0.00781697, -0.02294698, ..., -0.06647593,
        -0.01216047,  0.01780251],
       [ 0.0035793 , -0.00922786, -0.06279555, ...,  0.01276198,
         0.0185549 ,  0.00260469],
       ...,
       [ 0.00172665, -0.04116995, -0.05421981, ..., -0.02962246,
         0.04684817, -0.02997683],
       [-0.03567606, -0.03840322, -0.02236382, ..., -0.02362818,
        -0.05753163, -0.04622089],
       [-0.06830662,  0.00667038, -0.02941253, ...,  0.01675102,
        -0.02398688,  0.04903861]], dtype=float32)

In [88]:
X_train_new = pd.DataFrame(X_train)

In [106]:
X_train_new

0         1         2         3         4         5         6    \
0   -0.028341 -0.013976  0.027482  0.018902 -0.061030 -0.010846 -0.036913   
1   -0.014473 -0.037281  0.017812  0.027492  0.020230 -0.009877 -0.054037   
2   -0.022636 -0.001754 -0.009812 -0.030182 -0.061902  0.032183 -0.079847   
3   -0.040850 -0.023058 -0.033664  0.016514 -0.075332 -0.065355 -0.057857   
4    0.005932 -0.038425  0.048765  0.021749 -0.065592 -0.034451  0.007840   
..        ...       ...       ...       ...       ...       ...       ...   
708 -0.039573 -0.034612 -0.054511  0.002143 -0.069883 -0.021154 -0.007184   
709 -0.054486 -0.044427 -0.043594 -0.059228 -0.001342 -0.008159 -0.043861   
710 -0.020677 -0.008131 -0.052598 -0.055937 -0.014003  0.043405 -0.033968   
711 -0.018715 -0.034810 -0.021892 -0.013023 -0.024946 -0.036795 -0.013236   
712 -0.002041  0.017875 -0.030566  0.035613 -0.040723 -0.046850 -0.040547   

          7         8         9    ...       758       759       760  \
0   -0.034498  0.058866 -0.014550  ...  0.060303 -0.033084 -0.039746   
1    0.025131  0.029863 -0.029646  ... -0.002850 -0.043410 -0.012185   
2   -0.030968  0.012289  0.009093  ... -0.032143  0.016097 -0.052526   
3    0.007287 -0.013866 -0.010538  ... -0.054553  0.036248 -0.065568   
4   -0.012663  0.003260 -0.010410  ... -0.029770 -0.043370 -0.063726   
..        ...       ...       ...  ...       ...       ...       ...   
708  0.025463  0.016611 -0.034765  ... -0.004156 -0.024429 -0.039771   
709  0.024218 -0.055679  0.050908  ... -0.037053 -0.055940 -0.033750   
710 -0.023451  0.051850  0.015587  ... -0.023982  0.008298 -0.061214   
711  0.036843 -0.025344 -0.031787  ... -0.015544 -0.052263 -0.052117   
712 -0.035250 -0.015386  0.052649  ...  0.009394 -0.013508 -0.029466   

          761       762       763       764       765       766       767  
0    0.038668 -0.024701  0.000322 -0.077359  0.024810 -0.036909  0.045314  
1   -0.049657 -0.005346 -0.014185  0.005000 -0.007676  0.025819  0.036317  
2    0.046948 -0.007215  0.029919 -0.027418 -0.051822  0.014895 -0.043391  
3    0.011958  0.034914 -0.029956 -0.060300 -0.025076  0.040312  0.006233  
4   -0.004431 -0.012578 -0.062581 -0.068841 -0.040079 -0.040869 -0.014907  
..        ...       ...       ...       ...       ...       ...       ...  
708  0.003183  0.007217  0.026705 -0.053853  0.024176 -0.045959  0.038365  
709 -0.055441 -0.056849 -0.048494 -0.026811 -0.029099 -0.059161 -0.030108  
710 -0.002771 -0.014116  0.015934 -0.027618 -0.063385  0.008931 -0.051370  
711  0.002233 -0.019443  0.006502 -0.058433 -0.021675 -0.016809  0.056693  
712  0.046798 -0.053649 -0.051052 -0.051781 -0.003997 -0.028712 -0.016965  

[713 rows x 768 columns]

In [90]:
y_train_new = pd.DataFrame(y_train)

In [103]:
print(f"the {X_train_new.shape} shape of the X_train")
print(f"the {y_train_new.shape} shape of the y_train")

the (713, 768) shape of the X_train
the (1663, 1) shape of the y_train


In [98]:
#finding out the shape of the x_train
X_test_new = pd.DataFrame(X_test)
#printing out the results
print(f"the {X_test_new.shape} shape of the X_test")

the (713, 768) shape of the X_test


In [99]:
model = Sequential()

model.add(embedding_layer)
model.add(LSTM(32,dropout=0.2,recurrent_dropout=0.2))
model.add(Dense(32,activation='relu'))
#model.add(SimpleRNN(32, return_sequences=False))
#model.add(Dense(32,activation='tanh'))
model.add(Dense(45,activation='sigmoid'))
model.summary()


Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 50, 45)            9000      
_________________________________________________________________
lstm_6 (LSTM)                (None, 32)                9984      
_________________________________________________________________
dense_12 (Dense)             (None, 32)                1056      
_________________________________________________________________
dense_13 (Dense)             (None, 45)                1485      
Total params: 21,525
Trainable params: 21,525
Non-trainable params: 0
_________________________________________________________________


In [100]:
model.compile(optimizer='adam',
             loss='binary_crossentropy',
             metrics=['accuracy'])

In [101]:
model.fit(X_train_new,y_train_new,batch_size=32,epochs=10)

ValueError: Data cardinality is ambiguous:
  x sizes: 713
  y sizes: 1663
Make sure all arrays contain the same number of samples.