<a href="https://www.kaggle.com/code/mahendrasinghrajpoot/sinch-intent-detection?scriptVersionId=106856131" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Intent Detection

> Importing the libraries

In [1]:
import numpy as np
import pandas as pd

X_train = np.load('../input/intent-detection-by-sinch/X_train.npy')
X_test = np.load('../input/intent-detection-by-sinch/X_test.npy')

y_train = pd.read_csv('../input/intent-detection-by-sinch/y_train.csv').Predicted.to_numpy()#converting it into an numpy array.

In [2]:
def eda_data(X_train , X_test ,y_train):
    print("the dimension of x_train {}".format(X_train.ndim))
    print("the dimension of x_test {}".format(X_test.ndim))
    print("the shape of x_train {}".format(X_train.shape))
    print("the shape of x_test {}".format(X_test.shape))
    print("the size of x_train {}".format(X_train.size))
    print("the size of x_test {}".format(X_test.size))
    print("the size of y_train{}".format(y_train.shape))
    
    

In [3]:
eda_data(X_train,X_test,y_train)

the dimension of x_train 2
the dimension of x_test 2
the shape of x_train (1663, 768)
the shape of x_test (713, 768)
the size of x_train 1277184
the size of x_test 547584
the size of y_train(1663,)


In [4]:
X_train[:10]

array([[-0.06471267,  0.02055361, -0.06917297, ..., -0.02007275,
        -0.052884  ,  0.02371432],
       [-0.00638058,  0.00781697, -0.02294698, ..., -0.06647593,
        -0.01216047,  0.01780251],
       [ 0.0035793 , -0.00922786, -0.06279555, ...,  0.01276198,
         0.0185549 ,  0.00260469],
       ...,
       [-0.03657193, -0.03249233, -0.04902271, ..., -0.02548403,
        -0.00615544,  0.00632733],
       [-0.09880348, -0.00711128, -0.0496961 , ...,  0.04092421,
        -0.03646911, -0.01291262],
       [-0.03984436, -0.00512383, -0.06740589, ...,  0.0279867 ,
        -0.05178341, -0.02997069]], dtype=float32)

In [5]:
X_test[0:5]

array([[-0.02834134, -0.0139755 ,  0.02748156, ...,  0.02481022,
        -0.03690887,  0.04531401],
       [-0.01447345, -0.0372807 ,  0.01781211, ..., -0.00767628,
         0.02581855,  0.0363168 ],
       [-0.02263621, -0.00175439, -0.00981159, ..., -0.05182212,
         0.01489526, -0.04339051],
       [-0.04085005, -0.02305806, -0.03366361, ..., -0.02507613,
         0.04031206,  0.00623322],
       [ 0.00593197, -0.03842481,  0.04876529, ..., -0.04007944,
        -0.0408687 , -0.01490707]], dtype=float32)

In [6]:
y_train[0:3]

array([ 8, 44, 11])

Training the model for the intent detection on the top of the preformatted data or tokenized data.

In [7]:
#loading the sample file into the system 
sample = pd.read_csv("../input/intent-detection-by-sinch/sample.csv")
sample.shape

(713, 2)

In [8]:
import math
from sklearn.model_selection import train_test_split

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

#fiting the model to the dataset
logreg = LogisticRegression()
logreg.fit(X_train,y_train)

#finding out the accuracy on the test dataset intead of the using some other classification 

y_pred = logreg.predict(X_test)

#printing out the classification report of the dataset        
#print("The classification report of the above dataset is{}".format(classification_report(y_train,y_pred)))
#submission = pd.DataFrame({'id':sample['Id'],'Predicted':y_pred})

In [10]:
#submission.to_csv('submission.csv',index=False)

In [11]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=100)
knn.fit(X_train,y_train)
#making the prediction using the k neares neighbors and checking our the accuracy our of it
y_pred_knn = knn.predict(X_test)
#making the submission file
submission = pd.DataFrame({'id':sample['Id'],'Predicted':y_pred_knn})


In [12]:
submission.to_csv('submission.csv',index=False)